# Generated by Django 3.2 on 2022-05-01 07:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220428_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_video'),
        ),
    ]
