# Generated by Django 3.2 on 2022-05-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220510_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pending_friends_in',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pending_friends_out',
        ),
    ]
