# Generated by Django 3.2 on 2022-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20220331_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
