# Generated by Django 3.2 on 2022-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
