# Generated by Django 3.2 on 2022-03-17 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequest_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
