# Generated by Django 3.2 on 2022-05-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_postevent_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postevent',
            options={'ordering': ['-timestamp']},
        ),
    ]
