# Generated by Django 3.2 on 2022-05-16 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_video'),
        ('feed', '0006_friendrequestdeclinedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentevent',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_events', to='posts.comment'),
            preserve_default=False,
        ),
    ]
