# Generated by Django 3.2 on 2022-04-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='updated_at',
            new_name='last_message_at',
        ),
    ]
