# Generated by Django 3.2 on 2022-05-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20220416_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='has_media',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
    ]
